language: ruby

branches:
  only:
    - development

bundler_args: --without development debug

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

before_script:
  - cp config/database.yml.travis config/database.yml
