language: ruby

branches:
  only:
    - development

bundler_args: --without development debug

gobal:
  - RAILS_ENV=test
env:
  - DB=postgresql

script:
  - bundle exec rake db:setup --trace
  - bundle exec rake db:test:prepare
