
development:
  adapter: postgresql
  encoding: unicode
  database: dol-challenge_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: dol-challenge_test
  min_messages: warning
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: dol-challenge_production
  pool: 5
