
development:
  adapter: postgresql
  encoding: unicode
  database: dol-challenge_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: dol-challenge_test
  username: postgres
  min_messages: warning
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: dol-challenge_production
  pool: 5
